notify:
  email:
    recipients:
      - juan.baptiste@gmail.com
    from: $$SMTP_FROM
    host: $$SMTP_HOST
    port: $$SMTP_PORT
    username: $$SMTP_USERNAME
    password: $$SMTP_PASSWORD
publish:
  docker:
    registry: registry.ctecsas.com
    username: $$DOCKER_USER
    password: $$DOCKER_PASSWORD
    email: $$DOCKER_EMAIL
    repo: cachesimple/netstorage
    tag:
      - latest
      - $$COMMIT
    file: Dockerfile
    load: docker/image.tar
    save:
      destination: docker/image.tar
      tag: latest
    environment:
      - DOCKER_LAUNCH_DEBUG=true
    ##Temporal fix while running on CentOS
    #storage_driver: vfs
  cache:
    mount:
      - docker/image.tar
