postfix:
  image: juanluisbaptiste/postfix:latest
  expose:
  - "25"
  env_file: ../../credentials-smtp.env
netstorage:
  build: .
  links:
  - postfix:postfix
  volumes:
  - /reports
#   - /var/lib/akamai/
#   - ../../../../cachesimple-scripts:/cachesimple-scripts
#   environment:
#     - REMOTEPATH=35985/
# #    - NO_REPORT="iqmetrix evonik realworldtraining"
# #    - NO_REPORT="d2moto dist708234 florah index.html jbaptiste miikka mobilize otherside thingd truckingunlimited vivacity website"
#   privileged: true
