version: '3.7'

services:
  postfix:
    image: juanluisbaptiste/postfix:latest
    expose:
      - "25"
    env_file: credentials-smtp.env
  netstorage:
    image: juanluisbaptiste/netstorage-report:latest
    links:
      - postfix:postfix
    volumes:
      - ./reports:/reports
      - /home/juancho/.netstoragekit.json:/root/.netstoragekit.json
    environment:
      - REMOTEPATH=/
      - SMTP_TO=juan.baptiste@gmail.com
