postfix:
  image: juanluisbaptiste/postfix:latest
  expose:
  - "25"
  env_file: ../../credentials-smtp.env
netstorage:
  build: .
  links:
  - postfix:postfix
  volumes:
  - /reports
  - /home/juancho/.netstoragekit.json:/root/.netstoragekit.json
#   - /var/lib/akamai/
#   - ../../../../cachesimple-scripts:/cachesimple-scripts
  environment:
     - REMOTEPATH=/
     - SMTP_TO=jbaptiste@cachesimple.com,juan.baptiste@gmail.com
