postfix:
  image: juanluisbaptiste/postfix:latest
  expose: 
  - "25"
  env_file: ../../credentials-smtp.env
netstorage:
  build: .
  links:
  - postfix:postfix
  volumes:
  - /var/lib/akamai/
  - ../../../../cachesimple-scripts:/cachesimple-scripts
  environment:
    - REMOTEPATH=35985/mobilize
#    - NO_REPORT="iqmetrix evonik realworldtraining"
    - NO_REPORT="web"
  privileged: true

  